<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="./ejercicio-ii-1a-dtd.css"?>

<!DOCTYPE fichero [
		<!ELEMENT fichero (ficha+)>
		<!ELEMENT ficha (nombre, apellido, direccion*, DUI, nacionalidad?)>
		<!ELEMENT nombre (#PCDATA)>
		<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED >
      <!ATTLIST nombre edad  CDATA  #IMPLIED>
		<!ELEMENT apellido (#PCDATA)>
		<!ELEMENT direccion (#PCDATA)>
		<!ELEMENT DUI (#PCDATA)>
      <!ELEMENT nacionalidad (#PCDATA)>
      <!ATTLIST nacionalidad idioma CDATA "ingles">
		]>
<fichero>
 <ficha>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
  <DUI>12365875-0</DUI>
  <nacionalidad idioma="EspaÃ±ol">El Salvador</nacionalidad>
 </ficha>
</fichero>