=== TPI2021-UES/grupo-8-guia32/xmlvalido_GRUPO08/Archivos_Guia32_XML_Valido_DTD/Ejercicios/dtd_exterma/2a.dtd
<!ELEMENT fichero (webside, ficha+)>
<!ELEMENT ficha (nombre, apellido, direccion*, DUI, nacionalidad?)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED >
<!ATTLIST nombre edad  CDATA  #IMPLIED>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT DUI (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ATTLIST nacionalidad idioma CDATA "ingles">
<!ELEMENT webside (a)>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a  
  href CDATA #IMPLIED
  xmlns CDATA #IMPLIED 
  target (_blank|_self|marco) "_self">

=== TPI2021-UES/grupo-8-guia32/xmlvalido_GRUPO08/Archivos_Guia32_XML_Valido_DTD/Ejercicios/dtd_exterma/ejercicio-ii-2a-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="./ejercicio-ii-2a-dtd.css"?>

<!DOCTYPE fichero SYSTEM "2a.dtd">

<fichero>
<website>
    <a xmlns="http://www.w3.org/1999/xhtml" href="../../index.html">Regresar</a>
</website>
 <ficha>
  <nombre sexo="femenino" edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
  <DUI>12365875-0</DUI>
  <nacionalidad idioma="EspaÃ±ol">El Salvador</nacionalidad>
 </ficha>
</fichero>
