=== TPI2021-UES/grupo-8-guia32/xmlvalido_GRUPO08/Archivos_Guia32_XML_Valido_DTD/Ejercicios/dtd_exterma/tareas.dtd
<!--DTD del ejercicio III-->
<!ELEMENT universidad (webside, facultad+)>
<!ATTLIST universidad nombre (ues|uca|utec|unam) #FIXED "ues">
<!ELEMENT facultad (carrera)>
<!ATTLIST facultad nombre (fia) #REQUIRED>
<!ELEMENT carrera (asignatura)>
<!ATTLIST carrera nombre CDATA #IMPLIED>
<!ELEMENT asignatura (equipo)*>
<!ATTLIST asignatura nombre CDATA #IMPLIED>
<!ATTLIST asignatura codigo CDATA #REQUIRED>
<!ATTLIST asignatura uv CDATA #REQUIRED>
<!ELEMENT equipo (miembro+, encargado, actividad)>
<!ATTLIST equipo tipo (discucion|laboratorio|teorico) #FIXED "laboratorio">
<!ATTLIST equipo numero CDATA #REQUIRED>
<!ELEMENT miembro EMPTY>
<!ATTLIST miembro carnet CDATA #REQUIRED>
<!ATTLIST miembro nombre CDATA #IMPLIED>
<!ATTLIST miembro coordinador (si|no) "no">
<!ELEMENT encargado EMPTY>
<!ATTLIST encargado nombre CDATA #REQUIRED>
<!ELEMENT actividad EMPTY>
<!ATTLIST actividad nombre CDATA #REQUIRED>
<!ATTLIST actividad porcentaje CDATA #REQUIRED>
<!ELEMENT webside (a)>
<!ELEMENT a (#PCDATA)>
<!ATTLIST a  
  href CDATA #IMPLIED
  xmlns CDATA #IMPLIED 
  target (_blank|_self|marco) "_self">

=== TPI2021-UES/grupo-8-guia32/xmlvalido_GRUPO08/Archivos_Guia32_XML_Valido_DTD/Ejercicios/dtd_exterma/tareas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="./tareas.css"?>

<!DOCTYPE universidad SYSTEM "tareas.dtd">

<!--Ejemplo de implementación de la dtd-->

<universidad>
<facultad nombre="fia">
<carrera nombre="Ingenieria de Sistemas Informaticos">
<asignatura nombre="Teoria de Sistemas" codigo="TSI115" uv="4.0">
<equipo tipo="laboratorio" numero="08">
<miembro carnet="TJ19017" coordinador="si"/>
<miembro carnet="CD19018"/>
<miembro carnet="HZ13025"/>
<miembro carnet="JL17054"/>
<encargado nombre="Ing. Pablo Aguirre"/>
<actividad nombre="Investigacion sobre La teoria del caos" porcentaje="30%"/>
</equipo>
</asignatura>
</carrera>
</facultad>
</universidad>
